
optics_params = [
    {'min_samples': 6, 'xi': 0.02, 'min_cluster_size': 0.1},
    {'min_samples': 10, 'xi': 0.05, 'min_cluster_size': 0.1},
    {'min_samples': 7, 'xi': 0.03, 'min_cluster_size': 0.15},
    {'min_samples': 8, 'xi': 0.02, 'min_cluster_size': 0.05},
    {'min_samples': 9, 'xi': 0.1, 'min_cluster_size': 0.1},
    {'min_samples': 11, 'xi': 0.03, 'min_cluster_size': 0.1},
    {'min_samples': 7, 'xi': 0.05, 'min_cluster_size': 0.1},
    {'min_samples': 9, 'xi': 0.07, 'min_cluster_size': 0.1},
    {'min_samples': 6, 'xi': 0.1, 'min_cluster_size': 0.1},
    {'min_samples': 12, 'xi': 0.02, 'min_cluster_size': 0.15},
    {'min_samples': 9, 'xi': 0.07, 'min_cluster_size': 0.15},
    {'min_samples': 10, 'xi': 0.02, 'min_cluster_size': 0.15},
    {'min_samples': 11, 'xi': 0.02, 'min_cluster_size': 0.15},
    {'min_samples': 10, 'xi': 0.07, 'min_cluster_size': 0.1},
    {'min_samples': 5, 'xi': 0.03, 'min_cluster_size': 0.1},
    {'min_samples': 7, 'xi': 0.02, 'min_cluster_size': 0.1},
    {'min_samples': 5, 'xi': 0.03, 'min_cluster_size': 0.1},
    {'min_samples': 12, 'xi': 0.05, 'min_cluster_size': 0.1},
    {'min_samples': 13, 'xi': 0.05, 'min_cluster_size': 0.1},
    {'min_samples': 8, 'xi': 0.1, 'min_cluster_size': 0.15},
    {'min_samples': 6, 'xi': 0.02, 'min_cluster_size': 0.1},
    {'min_samples': 12, 'xi': 0.1, 'min_cluster_size': 0.1},
    {'min_samples': 5, 'xi': 0.05, 'min_cluster_size': 0.15},
    {'min_samples': 13, 'xi': 0.07, 'min_cluster_size': 0.1},
    {'min_samples': 8, 'xi': 0.07, 'min_cluster_size': 0.05},
    {'min_samples': 9, 'xi': 0.03, 'min_cluster_size': 0.1},
    {'min_samples': 6, 'xi': 0.03, 'min_cluster_size': 0.1},
    {'min_samples': 8, 'xi': 0.02, 'min_cluster_size': 0.1},
    {'min_samples': 9, 'xi': 0.05, 'min_cluster_size': 0.05},
    {'min_samples': 5, 'xi': 0.02, 'min_cluster_size': 0.15}
]


meanshift_params = [{'bandwidth': 3.0}, {'bandwidth': 3.05}, {'bandwidth': 3.1}, {'bandwidth': 3.15},
                    {'bandwidth': 3.2}, {'bandwidth': 3.25}, {'bandwidth': 3.3}, {'bandwidth': 3.35},
                    {'bandwidth': 3.4}, {'bandwidth': 3.45}, {'bandwidth': 3.5}, {'bandwidth': 3.55},
                    {'bandwidth': 3.6}, {'bandwidth': 3.65}, {'bandwidth': 3.7}, {'bandwidth': 3.75},
                    {'bandwidth': 3.8}, {'bandwidth': 3.85}, {'bandwidth': 3.9}, {'bandwidth': 3.95},
                    {'bandwidth': 4.0}, {'bandwidth': 4.05}, {'bandwidth': 4.1}, {'bandwidth': 4.15},
                    {'bandwidth': 4.2}, {'bandwidth': 4.25}, {'bandwidth': 4.3}, {'bandwidth': 4.35},
                    {'bandwidth': 4.4}, {'bandwidth': 4.45}, {'bandwidth': 4.5}, {'bandwidth': 4.55},
                    {'bandwidth': 4.6}, {'bandwidth': 4.65}, {'bandwidth': 4.7}, {'bandwidth': 4.75},
                    {'bandwidth': 4.8}, {'bandwidth': 4.85}, {'bandwidth': 4.9}, {'bandwidth': 4.95},
                    {'bandwidth': 5.0}, {'bandwidth': 5.05}, {'bandwidth': 5.1}, {'bandwidth': 5.15},
                    {'bandwidth': 5.2}, {'bandwidth': 5.25}, {'bandwidth': 5.3}, {'bandwidth': 5.35},
                    {'bandwidth': 5.4}, {'bandwidth': 5.45}, {'bandwidth': 5.5}, {'bandwidth': 5.55},
                    {'bandwidth': 5.6}, {'bandwidth': 5.65}, {'bandwidth': 5.7}, {'bandwidth': 5.75},
                    {'bandwidth': 5.8}, {'bandwidth': 5.85}, {'bandwidth': 5.9}, {'bandwidth': 5.95}]

birch_params = [
    {'n_clusters': 2, 'threshold': 3.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 0.3, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 1.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 0.5, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 2.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 2.0, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 1.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 0.5, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 5.0, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 3.5, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 1.0, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 1.0, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 4.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 0.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 2.5, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 3.5, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 0.5, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 1.5, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 1.0, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 2.0, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 4.0, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 4.5, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 4.5, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 3.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 0.3, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 4.0, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 3.0, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 2.5, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 3.0, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 0.3, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 4.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 5.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 0.3, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 5.0, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 1.5, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 2.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 2.0, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 1.5, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 3.0, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 3.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 1.5, 'branching_factor': 75},
    {'n_clusters': 2, 'threshold': 3.5, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 4.5, 'branching_factor': 100},
    {'n_clusters': 2, 'threshold': 4.0, 'branching_factor': 25},
    {'n_clusters': 2, 'threshold': 5.0, 'branching_factor': 50},
    {'n_clusters': 2, 'threshold': 2.5, 'branching_factor': 25}]

